#! /bin/sh
#  ____ _____ 
# |  _ \_   _|  Derek Taylor (DistroTube)
# | | | || |  	http://www.youtube.com/c/DistroTube
# | |_| || |  	http://www.gitlab.com/dwt1/ 
# |____/ |_|  	
#        
# A customized bspwmrc for the bspwm window manager.
# https://github.com/baskerville/sxhkd
# https://github.com/baskerville/bspwm

#### AUTOSTART ####
#sxhkd &
pgrep -x sxhkd > /dev/null || sxhkd &
#picom &
#nitrogen --restore &
feh --bg-scale '/home/newmentos/Pictures/Wallpapers/Archlinux/Derek Taylor/0213.jpg'
#./.config/bspwm/panel.sh &
#~/.config/polybar/launch.sh &

#### MONITORS ####
#bspc monitor DisplayPort-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor DisplayPort-1 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-A-0 -d 1 2 3 4 5 6 7 8 9
#bspc monitor HDMI-1 -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7
#bspc monitor HDMI-1 -d 1 2 3 4 5 6 7
#bspc monitor HDMI-1 -d I II III IV V VI VII
#bspc monitor -d 1:一 2:二 3:三 4:四 5:五 6:六 7:七 8:八 9:九 10:十
#bspc monitor -d I:一 II:二 III:三 IV:四 V:五 VI:六 VII:七

#### BSPWM configuration ####
#bspc config border_radius                8
bspc config border_width                  2
bspc config window_gap                    10
bspc config top_padding                   20
bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0
bspc config single_monocle                false
bspc config click_to_focus                true
#bspc config click_to_focus               button1
bspc config split_ratio                   0.50
bspc config borderless_monocle            true
bspc config gapless_monocle               true
bspc config focus_by_distance             true
bspc config focus_follows_pointer         true
bspc config history_aware_focus           true
bspc config remove_disabled_monitors      true
bspc config merge_overlapping_monitors    true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#4c566a"
bspc config active_border_color	              "#1e1e1e"
bspc config focused_border_color	      "#5e81ac"
bspc config presel_feedback_color	      "#5e81ac"
bspc config urgent_border_color 	      "#dd2727"

#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-1)
xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI-A-0)

bspc rule -a Gimp desktop='^8' state=floating follow=off
bspc rule -a Chromium desktop='^2'
bspc rule -a "Tor Browser" desktop='^2' state=floating follow=on
bspc rule -a Brave-browser desktop='^2'
bspc rule -a nyxt desktop='^2' state=floating follow=on
bspc rule -a Opera  desktop='^2' state=floating follow=on
bspc rule -a Emacs desktop='^3' state=tiled follow=on
bspc rule -a DrRacket desktop='^3' state=tiled follow=on
bspc rule -a jetbrains-studio desktop='^3' manage=off follow=on
bspc rule -a Wine desktop='^4' state=floating follow=on
bspc rule -a winword.exe  desktop='^4'state=floating follow=on
bspc rule -a excel.exe  desktop='^4' state=floating follow=on
bspc rule -a DesktopEditors desktop='^4' state=floating follow=on
bspc rule -a libreoffice desktop='^4' state=floating follow=on
bspc rule -a libreoffice-writer desktop='^4' state=floating follow=on
bspc rule -a libreoffice-draw desktop='^4' state=floating follow=on
bspc rule -a libreoffice desktop='^4' state=floating follow=on
bspc rule -a ViberPC desktop='^5' follow=off
bspc rule -a TelegramDesktop desktop='^5' follow=off
bspc rule -a QuiteRss desktop='^5' follow=off
bspc rule -a Skype desktop='^5' state=floating follow=off
bspc rule -a Shortwave desktop='^6'
bspc rule -a whatsapp-nativefier-d52542 desktop='^5'
bspc rule -a mpv desktop='^6'
bspc rule -a VirtualBox desktop='^7'
bspc rule -a VirtualBox Machine desktop='^7'
bspc rule -a VirtualBox Manager desktop='^7'
bspc rule -a VirtualBoxVM desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
